name: tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
  
      - name: Install uv
        uses: astral-sh/setup-uv@v5
  
      - name: Run tests and publish coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: 8983cf45468691fc9a7c2449a5c1883f02741a3a5f1f8ec9f6d95f46ec19c6d2
        with:
          coverageCommand: uv run pytest --cov --cov-report=xml
